// Actual clubs and festivals
export const CLUB_FESTIVAL_NAMES = [
  "Culture Box",
  "Arch",
  "Karrusel",
  "themomentfestival",
  "The Moment",
  "byhavencopenhagen",
  "Søpavillonen",
  "Museo Club",
  "Rumors",
  "Hive",
  "Chateau Motel",
  "Dorsia",
  "Noho",
  "The Jane",
  "Baggen",
  "Vega",
  "Rust",
  "Den Anden Side",
  "Hangaren",
  "Module",
  "Tyrolia Bier Klub",
  "Sigurd Klubben",
  "Klub Werkstatt",
  "Aveant",
  "project_cph"
];

// Popular bars (separate from clubs to avoid duplication)
export const BAR_NAMES = [
  "jolenebar",
  "H15",
  "Godt Øl",
  "Joy",
  "farfarsbodega",
  "oldirishpub_copenhagen",
  "thejane_cph",
  "zefsidecph",
  "Mikkeller Bar",
  "Mikkeller & Friends",
  "Lidkoeb",
  "Brus",
  "Nebbiolo Winebar",
  "Kayak Bar",
  "Eiffel Bar",
  "Villa Vino",
  "Kongens Bar",
  "The Union Local",
  "Kjær & Sommerfeldt Wine Bar",
  "Cocks & Cows Bar",
  "Ørsted Ølbar",
  "Duck and Cover",
  "Blume",
  "Taphouse",
  "La Fontaine",
  "Aloë Cocktailbar",
  "Charlie's Bar",
  "Balderdash",
  "Peders",
  "Not Your Usual Wine Bar",
  "Strøm",
  "Karma Club",
  "Halvandet",
  "Generator Bar",
  "The Library Bar",
  "The Globe Irish Pub",
  "Southern Cross Pub",
  "Ved Stranden 10",
  "Bird",
  "Rosforth & Rosforth",
  "Café Intime",
  "Gensyn",
  "Bip Bip Bar",
  "Slowburn Taproom",
  "Ruby",
  "Brønnum",
  "K-Bar",
  "Bo-Bi Bar",
  "Bar'Vin",
  "Balthazar",
  "thefluffyduck.cph",
  "monin_danmark",
  "boulebar.dk",
  "bar9.denmark"
]; 